version: "3.8"

services:
  combined_service:
    build: .
    container_name: combined_service
    restart: always
    ports:
      - "8500:8500"
      - "8080:80"
      - "9090:9090"
    volumes:
      - ./haproxy/ssl/cert.pem:/etc/ssl/certs/custom_cert.pem:ro
      - ./haproxy/consul_config.hcl:/etc/consul/consul_config.hcl:ro
      - ./haproxy/haproxy.cfg:/haproxy.conf.tmpl:ro
