version: "3.8"

services:
  consul:
    image: consul:1.15.4
    container_name: consul
    restart: always
    networks:
      - consul
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
  haproxy:
    image: haproxy:2.2-alpine
    container_name: haproxy
    restart: always
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - consul
    ports:
      - "8080:80"
      - "9090:9090"

networks:
  consul:
    name: consul
    driver: bridge