//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.17 at 01:13:08 AM MSK 
//


package org.example.product;

import jakarta.xml.bind.annotation.*;

import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CreatePersonRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreatePersonRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="birthday" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="eye_color" type="{http://example.org/product}Color"/&gt;
 *         &lt;element name="nationality" type="{http://example.org/product}Country"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreatePersonRequest", propOrder = {
        "name",
        "birthday",
        "height",
        "eyeColor",
        "nationality"
})
public class CreatePersonRequest {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthday;
    protected double height;
    @XmlElement(name = "eye_color", required = true)
    @XmlSchemaType(name = "string")
    protected Color eyeColor;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected Country nationality;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the birthday property.
     *
     * @return possible object is
     * {@link XMLGregorianCalendar }
     */
    public XMLGregorianCalendar getBirthday() {
        return birthday;
    }

    /**
     * Sets the value of the birthday property.
     *
     * @param value allowed object is
     *              {@link XMLGregorianCalendar }
     */
    public void setBirthday(XMLGregorianCalendar value) {
        this.birthday = value;
    }

    /**
     * Gets the value of the height property.
     */
    public double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     */
    public void setHeight(double value) {
        this.height = value;
    }

    /**
     * Gets the value of the eyeColor property.
     *
     * @return possible object is
     * {@link Color }
     */
    public Color getEyeColor() {
        return eyeColor;
    }

    /**
     * Sets the value of the eyeColor property.
     *
     * @param value allowed object is
     *              {@link Color }
     */
    public void setEyeColor(Color value) {
        this.eyeColor = value;
    }

    /**
     * Gets the value of the nationality property.
     *
     * @return possible object is
     * {@link Country }
     */
    public Country getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     *
     * @param value allowed object is
     *              {@link Country }
     */
    public void setNationality(Country value) {
        this.nationality = value;
    }

}
