//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.17 at 01:13:08 AM MSK 
//


package org.example.product;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for CreateProductRequest complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CreateProductRequest"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="coordinates" type="{http://example.org/product}CreateCoordinatesRequest"/&gt;
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="unit_of_measure" type="{http://example.org/product}UnitOfMeasure" minOccurs="0"/&gt;
 *         &lt;element name="owner" type="{http://example.org/product}CreatePersonRequest" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreateProductRequest", propOrder = {
        "name",
        "coordinates",
        "price",
        "unitOfMeasure",
        "owner"
})
public class CreateProductRequest {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected CreateCoordinatesRequest coordinates;
    protected int price;
    @XmlElement(name = "unit_of_measure")
    @XmlSchemaType(name = "string")
    protected UnitOfMeasure unitOfMeasure;
    protected CreatePersonRequest owner;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the coordinates property.
     *
     * @return possible object is
     * {@link CreateCoordinatesRequest }
     */
    public CreateCoordinatesRequest getCoordinates() {
        return coordinates;
    }

    /**
     * Sets the value of the coordinates property.
     *
     * @param value allowed object is
     *              {@link CreateCoordinatesRequest }
     */
    public void setCoordinates(CreateCoordinatesRequest value) {
        this.coordinates = value;
    }

    /**
     * Gets the value of the price property.
     */
    public int getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     */
    public void setPrice(int value) {
        this.price = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     *
     * @return possible object is
     * {@link UnitOfMeasure }
     */
    public UnitOfMeasure getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     *
     * @param value allowed object is
     *              {@link UnitOfMeasure }
     */
    public void setUnitOfMeasure(UnitOfMeasure value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the owner property.
     *
     * @return possible object is
     * {@link CreatePersonRequest }
     */
    public CreatePersonRequest getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     *
     * @param value allowed object is
     *              {@link CreatePersonRequest }
     */
    public void setOwner(CreatePersonRequest value) {
        this.owner = value;
    }

}
