//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.17 at 02:50:21 AM MSK 
//


package org.example.product;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.example.product package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateProductRequest_QNAME = new QName("http://example.org/product", "CreateProductRequest");
    private final static QName _ProductResponse_QNAME = new QName("http://example.org/product", "ProductResponse");
    private final static QName _GetProductsRequest_QNAME = new QName("http://example.org/product", "GetProductsRequest");
    private final static QName _ProductListResponse_QNAME = new QName("http://example.org/product", "ProductListResponse");
    private final static QName _GetProductRequest_QNAME = new QName("http://example.org/product", "GetProductRequest");
    private final static QName _UpdateProductRequest_QNAME = new QName("http://example.org/product", "UpdateProductRequest");
    private final static QName _DeleteProductRequest_QNAME = new QName("http://example.org/product", "DeleteProductRequest");
    private final static QName _UniqueMeasurementsResponse_QNAME = new QName("http://example.org/product", "UniqueMeasurementsResponse");
    private final static QName _ColorsResponse_QNAME = new QName("http://example.org/product", "ColorsResponse");
    private final static QName _CountriesResponse_QNAME = new QName("http://example.org/product", "CountriesResponse");
    private final static QName _MeasuresResponse_QNAME = new QName("http://example.org/product", "MeasuresResponse");
    private final static QName _DeleteProductsByPriceRequest_QNAME = new QName("http://example.org/product", "DeleteProductsByPriceRequest");
    private final static QName _ErrorResponse_QNAME = new QName("http://example.org/product", "ErrorResponse");
    private final static QName _GetColorsRequest_QNAME = new QName("http://example.org/product", "GetColorsRequest");
    private final static QName _GetCountriesRequest_QNAME = new QName("http://example.org/product", "GetCountriesRequest");
    private final static QName _GetMeasuresRequest_QNAME = new QName("http://example.org/product", "GetMeasuresRequest");
    private final static QName _GetUniqueMeasurementsRequest_QNAME = new QName("http://example.org/product", "GetUniqueMeasurementsRequest");
    private final static QName _GetEarliestProductRequest_QNAME = new QName("http://example.org/product", "GetEarliestProductRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.product
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateProductRequest }
     */
    public CreateProductRequest createCreateProductRequest() {
        return new CreateProductRequest();
    }

    /**
     * Create an instance of {@link ProductResponse }
     */
    public ProductResponse createProductResponse() {
        return new ProductResponse();
    }

    /**
     * Create an instance of {@link GetProductsRequest }
     */
    public GetProductsRequest createGetProductsRequest() {
        return new GetProductsRequest();
    }

    /**
     * Create an instance of {@link ProductListResponse }
     */
    public ProductListResponse createProductListResponse() {
        return new ProductListResponse();
    }

    /**
     * Create an instance of {@link GetProductRequest }
     */
    public GetProductRequest createGetProductRequest() {
        return new GetProductRequest();
    }

    /**
     * Create an instance of {@link UpdateProductRequest }
     */
    public UpdateProductRequest createUpdateProductRequest() {
        return new UpdateProductRequest();
    }

    /**
     * Create an instance of {@link DeleteProductRequest }
     */
    public DeleteProductRequest createDeleteProductRequest() {
        return new DeleteProductRequest();
    }

    /**
     * Create an instance of {@link UniqueMeasurementsResponse }
     */
    public UniqueMeasurementsResponse createUniqueMeasurementsResponse() {
        return new UniqueMeasurementsResponse();
    }

    /**
     * Create an instance of {@link ColorsResponse }
     */
    public ColorsResponse createColorsResponse() {
        return new ColorsResponse();
    }

    /**
     * Create an instance of {@link CountriesResponse }
     */
    public CountriesResponse createCountriesResponse() {
        return new CountriesResponse();
    }

    /**
     * Create an instance of {@link MeasuresResponse }
     */
    public MeasuresResponse createMeasuresResponse() {
        return new MeasuresResponse();
    }

    /**
     * Create an instance of {@link DeleteProductsByPriceRequest }
     */
    public DeleteProductsByPriceRequest createDeleteProductsByPriceRequest() {
        return new DeleteProductsByPriceRequest();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link GetColorsRequest }
     */
    public GetColorsRequest createGetColorsRequest() {
        return new GetColorsRequest();
    }

    /**
     * Create an instance of {@link GetCountriesRequest }
     */
    public GetCountriesRequest createGetCountriesRequest() {
        return new GetCountriesRequest();
    }

    /**
     * Create an instance of {@link GetMeasuresRequest }
     */
    public GetMeasuresRequest createGetMeasuresRequest() {
        return new GetMeasuresRequest();
    }

    /**
     * Create an instance of {@link GetUniqueMeasurementsRequest }
     */
    public GetUniqueMeasurementsRequest createGetUniqueMeasurementsRequest() {
        return new GetUniqueMeasurementsRequest();
    }

    /**
     * Create an instance of {@link GetEarliestProductRequest }
     */
    public GetEarliestProductRequest createGetEarliestProductRequest() {
        return new GetEarliestProductRequest();
    }

    /**
     * Create an instance of {@link CreateCoordinatesRequest }
     */
    public CreateCoordinatesRequest createCreateCoordinatesRequest() {
        return new CreateCoordinatesRequest();
    }

    /**
     * Create an instance of {@link CreatePersonRequest }
     */
    public CreatePersonRequest createCreatePersonRequest() {
        return new CreatePersonRequest();
    }

    /**
     * Create an instance of {@link CoordinatesResponse }
     */
    public CoordinatesResponse createCoordinatesResponse() {
        return new CoordinatesResponse();
    }

    /**
     * Create an instance of {@link PersonResponse }
     */
    public PersonResponse createPersonResponse() {
        return new PersonResponse();
    }

    /**
     * Create an instance of {@link MetaResponse }
     */
    public MetaResponse createMetaResponse() {
        return new MetaResponse();
    }

    /**
     * Create an instance of {@link UpdatePersonRequest }
     */
    public UpdatePersonRequest createUpdatePersonRequest() {
        return new UpdatePersonRequest();
    }

    /**
     * Create an instance of {@link UpdateCoordinatesRequest }
     */
    public UpdateCoordinatesRequest createUpdateCoordinatesRequest() {
        return new UpdateCoordinatesRequest();
    }

    /**
     * Create an instance of {@link ErrorDetails }
     */
    public ErrorDetails createErrorDetails() {
        return new ErrorDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateProductRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link CreateProductRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "CreateProductRequest")
    public JAXBElement<CreateProductRequest> createCreateProductRequest(CreateProductRequest value) {
        return new JAXBElement<CreateProductRequest>(_CreateProductRequest_QNAME, CreateProductRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ProductResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "ProductResponse")
    public JAXBElement<ProductResponse> createProductResponse(ProductResponse value) {
        return new JAXBElement<ProductResponse>(_ProductResponse_QNAME, ProductResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductsRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link GetProductsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "GetProductsRequest")
    public JAXBElement<GetProductsRequest> createGetProductsRequest(GetProductsRequest value) {
        return new JAXBElement<GetProductsRequest>(_GetProductsRequest_QNAME, GetProductsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductListResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ProductListResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "ProductListResponse")
    public JAXBElement<ProductListResponse> createProductListResponse(ProductListResponse value) {
        return new JAXBElement<ProductListResponse>(_ProductListResponse_QNAME, ProductListResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link GetProductRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "GetProductRequest")
    public JAXBElement<GetProductRequest> createGetProductRequest(GetProductRequest value) {
        return new JAXBElement<GetProductRequest>(_GetProductRequest_QNAME, GetProductRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateProductRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link UpdateProductRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "UpdateProductRequest")
    public JAXBElement<UpdateProductRequest> createUpdateProductRequest(UpdateProductRequest value) {
        return new JAXBElement<UpdateProductRequest>(_UpdateProductRequest_QNAME, UpdateProductRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteProductRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link DeleteProductRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "DeleteProductRequest")
    public JAXBElement<DeleteProductRequest> createDeleteProductRequest(DeleteProductRequest value) {
        return new JAXBElement<DeleteProductRequest>(_DeleteProductRequest_QNAME, DeleteProductRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UniqueMeasurementsResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link UniqueMeasurementsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "UniqueMeasurementsResponse")
    public JAXBElement<UniqueMeasurementsResponse> createUniqueMeasurementsResponse(UniqueMeasurementsResponse value) {
        return new JAXBElement<UniqueMeasurementsResponse>(_UniqueMeasurementsResponse_QNAME, UniqueMeasurementsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ColorsResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ColorsResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "ColorsResponse")
    public JAXBElement<ColorsResponse> createColorsResponse(ColorsResponse value) {
        return new JAXBElement<ColorsResponse>(_ColorsResponse_QNAME, ColorsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CountriesResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link CountriesResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "CountriesResponse")
    public JAXBElement<CountriesResponse> createCountriesResponse(CountriesResponse value) {
        return new JAXBElement<CountriesResponse>(_CountriesResponse_QNAME, CountriesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeasuresResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link MeasuresResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "MeasuresResponse")
    public JAXBElement<MeasuresResponse> createMeasuresResponse(MeasuresResponse value) {
        return new JAXBElement<MeasuresResponse>(_MeasuresResponse_QNAME, MeasuresResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteProductsByPriceRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link DeleteProductsByPriceRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "DeleteProductsByPriceRequest")
    public JAXBElement<DeleteProductsByPriceRequest> createDeleteProductsByPriceRequest(DeleteProductsByPriceRequest value) {
        return new JAXBElement<DeleteProductsByPriceRequest>(_DeleteProductsByPriceRequest_QNAME, DeleteProductsByPriceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorResponse }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link ErrorResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "ErrorResponse")
    public JAXBElement<ErrorResponse> createErrorResponse(ErrorResponse value) {
        return new JAXBElement<ErrorResponse>(_ErrorResponse_QNAME, ErrorResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetColorsRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link GetColorsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "GetColorsRequest")
    public JAXBElement<GetColorsRequest> createGetColorsRequest(GetColorsRequest value) {
        return new JAXBElement<GetColorsRequest>(_GetColorsRequest_QNAME, GetColorsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCountriesRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link GetCountriesRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "GetCountriesRequest")
    public JAXBElement<GetCountriesRequest> createGetCountriesRequest(GetCountriesRequest value) {
        return new JAXBElement<GetCountriesRequest>(_GetCountriesRequest_QNAME, GetCountriesRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMeasuresRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link GetMeasuresRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "GetMeasuresRequest")
    public JAXBElement<GetMeasuresRequest> createGetMeasuresRequest(GetMeasuresRequest value) {
        return new JAXBElement<GetMeasuresRequest>(_GetMeasuresRequest_QNAME, GetMeasuresRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUniqueMeasurementsRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link GetUniqueMeasurementsRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "GetUniqueMeasurementsRequest")
    public JAXBElement<GetUniqueMeasurementsRequest> createGetUniqueMeasurementsRequest(GetUniqueMeasurementsRequest value) {
        return new JAXBElement<GetUniqueMeasurementsRequest>(_GetUniqueMeasurementsRequest_QNAME, GetUniqueMeasurementsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetEarliestProductRequest }{@code >}
     *
     * @param value Java instance representing xml element's value.
     * @return the new instance of {@link JAXBElement }{@code <}{@link GetEarliestProductRequest }{@code >}
     */
    @XmlElementDecl(namespace = "http://example.org/product", name = "GetEarliestProductRequest")
    public JAXBElement<GetEarliestProductRequest> createGetEarliestProductRequest(GetEarliestProductRequest value) {
        return new JAXBElement<GetEarliestProductRequest>(_GetEarliestProductRequest_QNAME, GetEarliestProductRequest.class, null, value);
    }

}
