//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.18 at 09:28:28 PM MSK 
//


package org.example.products;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.products package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.products
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateProductRequest }
     * 
     */
    public CreateProductRequest createCreateProductRequest() {
        return new CreateProductRequest();
    }

    /**
     * Create an instance of {@link CreateCoordinatesRequest }
     * 
     */
    public CreateCoordinatesRequest createCreateCoordinatesRequest() {
        return new CreateCoordinatesRequest();
    }

    /**
     * Create an instance of {@link CreatePersonRequest }
     * 
     */
    public CreatePersonRequest createCreatePersonRequest() {
        return new CreatePersonRequest();
    }

    /**
     * Create an instance of {@link CreateProductResponse }
     * 
     */
    public CreateProductResponse createCreateProductResponse() {
        return new CreateProductResponse();
    }

    /**
     * Create an instance of {@link CoordinatesResponse }
     * 
     */
    public CoordinatesResponse createCoordinatesResponse() {
        return new CoordinatesResponse();
    }

    /**
     * Create an instance of {@link PersonResponse }
     * 
     */
    public PersonResponse createPersonResponse() {
        return new PersonResponse();
    }

    /**
     * Create an instance of {@link GetProductsResponse }
     * 
     */
    public GetProductsResponse createGetProductsResponse() {
        return new GetProductsResponse();
    }

    /**
     * Create an instance of {@link ProductResponseType }
     * 
     */
    public ProductResponseType createProductResponseType() {
        return new ProductResponseType();
    }

    /**
     * Create an instance of {@link MetaResponse }
     * 
     */
    public MetaResponse createMetaResponse() {
        return new MetaResponse();
    }

    /**
     * Create an instance of {@link GetProductsRequest }
     * 
     */
    public GetProductsRequest createGetProductsRequest() {
        return new GetProductsRequest();
    }

    /**
     * Create an instance of {@link GetProductRequest }
     * 
     */
    public GetProductRequest createGetProductRequest() {
        return new GetProductRequest();
    }

    /**
     * Create an instance of {@link GetProductResponse }
     * 
     */
    public GetProductResponse createGetProductResponse() {
        return new GetProductResponse();
    }

    /**
     * Create an instance of {@link UpdateProductRequest }
     * 
     */
    public UpdateProductRequest createUpdateProductRequest() {
        return new UpdateProductRequest();
    }

    /**
     * Create an instance of {@link UpdateCoordinatesRequest }
     * 
     */
    public UpdateCoordinatesRequest createUpdateCoordinatesRequest() {
        return new UpdateCoordinatesRequest();
    }

    /**
     * Create an instance of {@link UpdatePersonRequest }
     * 
     */
    public UpdatePersonRequest createUpdatePersonRequest() {
        return new UpdatePersonRequest();
    }

    /**
     * Create an instance of {@link UpdateProductResponse }
     * 
     */
    public UpdateProductResponse createUpdateProductResponse() {
        return new UpdateProductResponse();
    }

    /**
     * Create an instance of {@link DeleteProductRequest }
     * 
     */
    public DeleteProductRequest createDeleteProductRequest() {
        return new DeleteProductRequest();
    }

    /**
     * Create an instance of {@link DeleteProductResponse }
     * 
     */
    public DeleteProductResponse createDeleteProductResponse() {
        return new DeleteProductResponse();
    }

    /**
     * Create an instance of {@link DeleteProductsByPriceRequest }
     * 
     */
    public DeleteProductsByPriceRequest createDeleteProductsByPriceRequest() {
        return new DeleteProductsByPriceRequest();
    }

    /**
     * Create an instance of {@link DeleteProductsByPriceResponse }
     * 
     */
    public DeleteProductsByPriceResponse createDeleteProductsByPriceResponse() {
        return new DeleteProductsByPriceResponse();
    }

    /**
     * Create an instance of {@link GetColorsRequest }
     * 
     */
    public GetColorsRequest createGetColorsRequest() {
        return new GetColorsRequest();
    }

    /**
     * Create an instance of {@link GetColorsResponse }
     * 
     */
    public GetColorsResponse createGetColorsResponse() {
        return new GetColorsResponse();
    }

    /**
     * Create an instance of {@link GetCountriesRequest }
     * 
     */
    public GetCountriesRequest createGetCountriesRequest() {
        return new GetCountriesRequest();
    }

    /**
     * Create an instance of {@link GetCountriesResponse }
     * 
     */
    public GetCountriesResponse createGetCountriesResponse() {
        return new GetCountriesResponse();
    }

    /**
     * Create an instance of {@link GetMeasuresRequest }
     * 
     */
    public GetMeasuresRequest createGetMeasuresRequest() {
        return new GetMeasuresRequest();
    }

    /**
     * Create an instance of {@link GetMeasuresResponse }
     * 
     */
    public GetMeasuresResponse createGetMeasuresResponse() {
        return new GetMeasuresResponse();
    }

    /**
     * Create an instance of {@link GetUniqueMeasurementsRequest }
     * 
     */
    public GetUniqueMeasurementsRequest createGetUniqueMeasurementsRequest() {
        return new GetUniqueMeasurementsRequest();
    }

    /**
     * Create an instance of {@link GetUniqueMeasurementsResponse }
     * 
     */
    public GetUniqueMeasurementsResponse createGetUniqueMeasurementsResponse() {
        return new GetUniqueMeasurementsResponse();
    }

    /**
     * Create an instance of {@link GetEarliestProductRequest }
     * 
     */
    public GetEarliestProductRequest createGetEarliestProductRequest() {
        return new GetEarliestProductRequest();
    }

    /**
     * Create an instance of {@link GetEarliestProductResponse }
     * 
     */
    public GetEarliestProductResponse createGetEarliestProductResponse() {
        return new GetEarliestProductResponse();
    }

}
