//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.19 at 12:52:30 AM MSK 
//


package org.example.products;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for unitOfMeasure.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <pre>
 * &lt;simpleType name="unitOfMeasure"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="METERS"/&gt;
 *     &lt;enumeration value="CENTIMETERS"/&gt;
 *     &lt;enumeration value="MILLIGRAMS"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "unitOfMeasure")
@XmlEnum
public enum UnitOfMeasure {

    METERS,
    CENTIMETERS,
    MILLIGRAMS;

    public String value() {
        return name();
    }

    public static UnitOfMeasure fromValue(String v) {
        return valueOf(v);
    }

}
